sudo: false

language: php

php:
    - 5.6.30
    - 7.3

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer require timber/timber
    - composer require phpunit/phpunit:5.7.16
    - composer install --dev

script:
    - vendor/phpunit/phpunit/phpunit
